### ISSUE TITLE
maxHP field can be null at render time

### ISSUE THREAD

**Issue by ajoshi** [ajoshi/KoLMiner#1]
```09-02 20:50:49.350 21711-21760/? I/flutter: The method '/' was called on null.
09-02 20:50:49.350 21711-21760/? I/flutter: Receiver: null
09-02 20:50:49.350 21711-21760/? I/flutter: Tried calling: /(null)
09-02 20:50:49.355 21711-21760/? I/flutter: When the exception was thrown, this was the stack:
09-02 20:50:49.355 21711-21760/? I/flutter: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46)
09-02 20:50:49.355 21711-21760/? I/flutter: #1      UserInfoState._buildHpMpBar (package:kol_miner/player_info/user_info_widget.dart:95)
09-02 20:50:49.355 21711-21760/? I/flutter: #2      UserInfoState._buildInfoBox (package:kol_miner/player_info/user_info_widget.dart:69)
09-02 20:50:49.355 21711-21760/? I/flutter: #3      UserInfoState.build (package:kol_miner/player_info/user_info_widget.dart:42)
09-02 20:50:49.355 21711-21760/? I/flutter: #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3730)
09-02 20:50:49.355 21711-21760/? I/flutter: #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3642)
09-02 20:50:49.355 21711-21760/? I/flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3495)
09-02 20:50:49.355 21711-21760/? I/flutter: #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2242)
09-02 20:50:49.355 21711-21760/? I/flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBindin```

**Comment by ajoshi** [comment]
This happens when the user isn't supposed to be logged in. Use should have seen 'username or password incorrect' message instead
