### ISSUE TITLE
App does not gracefully exit if mine access is revoked while getting new mine

### ISSUE THREAD

**Issue by ajoshi** [ajoshi/KoLMiner#9]
I/flutter (28677): mining randomly so we can gtfo
I/flutter (28677): mined at (2,6). shiny? false isFront? true pri: 4
I/flutter (28677): need a new mine
I/flutter (28677): we need a new mine and we can get one
I/flutter (28677): got a new mine!
I/flutter (28677): mined at (2,6). shiny? true isFront? true pri: 4
I/flutter (28677): mined at (3,6). shiny? true isFront? true pri: 3
I/flutter (28677): mined at (4,6). shiny? true isFront? true pri: 2
I/flutter (28677): need a new mine
I/flutter (28677): mining randomly so we can gtfo
E/flutter (28677): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: No element
E/flutter (28677): #0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
E/flutter (28677): #1      Mine.getThrowawayMineSquare (package:kol_miner/mining/mine.dart:69:20)
E/flutter (28677): #2      Miner.mineNextSquare (package:kol_miner/mining/miner.dart:76:39)
E/flutter (28677): #3      MiningPageState.mineNtimes (package:kol_miner/mining/widget/mining_page.dart:69:34)
E/flutter (28677): <asynchronous suspension>

Case: Lost protection while mining/getting new mine

**Comment by ajoshi** [comment]
https://github.com/ajoshi/KoLMiner/commit/d2b4f119af0c513a2d13399af69dfc07eac999fc
